apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: namelist
  labels:
    app: namelist
    component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "mypassword"
  DB_PASSWORD: "mypassword"
